fighter_verses = {
    '1': {  'year':'1',
            'week':'1:01',
            'topic':'Faithfulness (of God)',
            'verse':'Deuteronomy+7:9' },
    '2': {  'year':'1',
            'week':'1:02',
            'topic':'Obeying God',
            'verse':'Deuteronomy+10:12-13' },
    '3': {  'year':'1',
            'week':'1:03',
            'topic':'Salvation',
            'verse':'John+1:12-13' },
    '4': {  'year':'1',
            'week':'1:04',
            'topic':'Sovereignty of God',
            'verse':'Romans+11:33-36' },
    '5': {  'year':'1',
            'week':'1:05',
            'topic':'Sanctification',
            'verse':'Romans+12:1-2' },
    '6': {  'year':'1',
            'week':'1:06',
            'topic':'Fear, Battling',
            'verse':'Psalm+56:3-4' },
    '7': {  'year':'1',
            'week':'1:07',
            'topic':'Trusting God',
            'verse':'Psalm+62:5-8' },
    '8': {  'year':'1',
            'week':'1:08',
            'topic':'Work of Christ',
            'verse':'Romans+8:1' },
    '9': {  'year':'1',
            'week':'1:09',
            'topic':'Sin, Battling',
            'verse':'1John+2:15-17' },
    '10': {  'year':'1',
             'week':'1:10',
             'topic':'Humility of Christ',
             'verse':'Philippians+2:5-7' },
    '11': {  'year':'1',
             'week':'1:11',
             'topic':'Humility of Christ',
             'verse':'Philippians+2:8-9' },
    '12': {  'year':'1',
             'week':'1:12',
             'topic':'Supremacy of Jesus',
             'verse':'Philippians+2:10-11' },
    '13': {  'year':'1',
             'week':'1:13',
             'topic':'Sanctification',
             'verse':'Philippians+2:12-13' },
    '14': {  'year':'1',
             'week':'1:14',
             'topic':'Endurance',
             'verse':'James+1:2-3' },
    '15': {  'year':'1',
             'week':'1:15',
             'topic':'Endurance',
             'verse':'James+1:4-5' },
    '16': {  'year':'1',
             'week':'1:16',
             'topic':'Word of the Lord',
             'verse':'Psalm+1:1-2' },
    '17': {  'year':'1',
             'week':'1:17',
             'topic':'Word of the Lord',
             'verse':'Psalm+1:3-4' },
    '18': {  'year':'1',
             'week':'1:18',
             'topic':'Word of the Lord',
             'verse':'Psalm+1:5-6' },
    '19': {  'year':'1',
             'week':'1:19',
             'topic':'Life in Christ',
             'verse':'Colossians+3:1-3' },
    '20': {  'year':'1',
             'week':'1:20',
             'topic':'Anger, Battling',
             'verse':'Ephesians+4:26' },
    '21': {  'year':'1',
             'week':'1:21',
             'topic':'Sovereignty of God',
             'verse':'Isaiah+40:28-29' },
    '22': {  'year':'1',
             'week':'1:22',
             'topic':'Waiting on God',
             'verse':'Isaiah+40:30-31' },
    '23': {  'year':'1',
             'week':'1:23',
             'topic':'Faithfulness (of God)',
             'verse':'Psalm+86:5-7' },
    '24': {  'year':'1',
             'week':'1:24',
             'topic':'Supremacy of Jesus',
             'verse':'1Timothy+2:5' },
    '25': {  'year':'1',
             'week':'1:25',
             'topic':'Salvation',
             'verse':'1Peter+1:3-5 ' },
    '26': {  'year':'1',
             'week':'1:26',
             'topic':'Spiritual Warfare',
             'verse':'Ephesians+6:10-11' },
    '27': {  'year':'1',
             'week':'1:27',
             'topic':'Spiritual Warfare',
             'verse':'Ephesians+6:12-13' },
    '28': {  'year':'1',
             'week':'1:28',
             'topic':'Spiritual Warfare',
             'verse':'Ephesians+6:14-15' },
    '29': {  'year':'1',
             'week':'1:29',
             'topic':'Spiritual Warfare',
             'verse':'Ephesians+6:16-18' },
    '30': {  'year':'1',
             'week':'1:30',
             'topic':'Security in God',
             'verse':'Philippians+1:6' },
    '31': {  'year':'1',
             'week':'1:31',
             'topic':'Fear, Battling',
             'verse':'Matthew+10:28' },
    '32': {  'year':'1',
             'week':'1:32',
             'topic':'Gospel',
             'verse':'Romans+1:17' },
    '33': {  'year':'1',
             'week':'1:33',
             'topic':'Depending on Christ',
             'verse':'Matthew+11:28-30' },
    '34': {  'year':'1',
             'week':'1:34',
             'topic':'Trusting God',
             'verse':'Psalm+20:6-8' },
    '35': {  'year':'1',
             'week':'1:35',
             'topic':'Endurance',
             'verse':'James+1:12' },
    '36': {  'year':'1',
             'week':'1:36',
             'topic':'Generosity',
             'verse':'2Corinthians+9:6-7' },
    '37': {  'year':'1',
             'week':'1:37',
             'topic':'Generosity',
             'verse':'2Corinthians+9:8' },
    '38': {  'year':'1',
             'week':'1:38',
             'topic':'Depending on Christ',
             'verse':'2Corinthians+12:10' },
    '39': {  'year':'1',
             'week':'1:39',
             'topic':'Waiting on God',
             'verse':'Isaiah+64:4' },
    '40': {  'year':'1',
             'week':'1:40',
             'topic':'Work of Christ',
             'verse':'Titus+3:4-6' },
    '41': {  'year':'1',
             'week':'1:41',
             'topic':'Sovereignty of God',
             'verse':'Isaiah+46:9-11' },
    '42': {  'year':'1',
             'week':'1:42',
             'topic':'Sin, Battling',
             'verse':'Proverbs+1:10' },
    '43': {  'year':'1',
             'week':'1:43',
             'topic':'Trusting God',
             'verse':'Proverbs+3:5-7' },
    '44': {  'year':'1',
             'week':'1:44',
             'topic':'Anger, Battling',
             'verse':'Proverbs+19:11' },
    '45': {  'year':'1',
             'week':'1:45',
             'topic':'Life in Christ',
             'verse':'John+15:5' },
    '46': {  'year':'1',
             'week':'1:46',
             'topic':'Eternity',
             'verse':'John+14:2-3' },
    '47': {  'year':'1',
             'week':'1:47',
             'topic':'Trusting God',
             'verse':'Psalm+125:1-2' },
    '48': {  'year':'1',
             'week':'1:48',
             'topic':'Speech',
             'verse':'Psalm+141:3-4' },
    '49': {  'year':'1',
             'week':'1:49',
             'topic':'Sin, Battling',
             'verse':'1John+1:8-9' },
    '50': {  'year':'1',
             'week':'1:50',
             'topic':'Guidance (of God)',
             'verse':'Psalm+23:1-2' },
    '51': {  'year':'1',
             'week':'1:51',
             'topic':'Guidance (of God)',
             'verse':'Psalm+23:3-4' },
    '52': {  'year':'1',
             'week':'1:52',
             'topic':'Presence (of God)',
             'verse':'Psalm+23:5-6' },
    '53': {  'year':'2',
             'week':'2:01',
             'topic':'Word of the Lord',
             'verse':'Isaiah+40:8' },
    '54': {  'year':'2',
             'week':'2:02',
             'topic':'Gospel',
             'verse':'Romans+10:13-15' },
    '55': {  'year':'2',
             'week':'2:03',
             'topic':'Joy',
             'verse':'Psalm+16:11' },
    '56': {  'year':'2',
             'week':'2:04',
             'topic':'Life in Christ',
             'verse':'Romans+15:1-2' },
    '57': {  'year':'2',
             'week':'2:05',
             'topic':'Goodness (of God)',
             'verse':'Psalm+103:1-4' },
    '58': {  'year':'2',
             'week':'2:06',
             'topic':'Goodness (of God)',
             'verse':'Psalm+103:5-7' },
    '59': {  'year':'2',
             'week':'2:07',
             'topic':'Goodness (of God)',
             'verse':'Psalm+103:8-10' },
    '60': {  'year':'2',
             'week':'2:08',
             'topic':'Goodness (of God)',
             'verse':'Psalm+103:11-14' },
    '61': {  'year':'2',
             'week':'2:09',
             'topic':'Goodness (of God)',
             'verse':'Psalm+103:15-16' },
    '62': {  'year':'2',
             'week':'2:10',
             'topic':'Goodness (of God)',
             'verse':'Psalm+103:17-19' },
    '63': {  'year':'2',
             'week':'2:11',
             'topic':'Praise & Worship',
             'verse':'Psalm+103:20-22' },
    '64': {  'year':'2',
             'week':'2:12',
             'topic':'Guidance (of God)',
             'verse':'Psalm+86:11' },
    '65': {  'year':'2',
             'week':'2:13',
             'topic':'Speech',
             'verse':'Ephesians+4:29' },
    '66': {  'year':'2',
             'week':'2:14',
             'topic':'Sanctification',
             'verse':'Ephesians+4:31-32' },
    '67': {  'year':'2',
             'week':'2:15',
             'topic':'Loving God',
             'verse':'Deuteronomy+6:4-5' },
    '68': {  'year':'2',
             'week':'2:16',
             'topic':'Word of the Lord',
             'verse':'Deuteronomy+6:6-7' },
    '69': {  'year':'2',
             'week':'2:17',
             'topic':'Life in Christ',
             'verse':'2Corinthians+5:17' },
    '70': {  'year':'2',
             'week':'2:18',
             'topic':'Generosity',
             'verse':'Luke+12:32-34' },
    '71': {  'year':'2',
             'week':'2:19',
             'topic':'Sanctification',
             'verse':'Galatians+5:22-23' },
    '72': {  'year':'2',
             'week':'2:20',
             'topic':'Sanctification',
             'verse':'Galatians+5:24-25' },
    '73': {  'year':'2',
             'week':'2:21',
             'topic':'Obeying God',
             'verse':'Proverbs+6:20-21' },
    '74': {  'year':'2',
             'week':'2:22',
             'topic':'Word of the Lord',
             'verse':'Proverbs+6:22-23' },
    '75': {  'year':'2',
             'week':'2:23',
             'topic':'Contentment',
             'verse':'Philippians+4:11-13' },
    '76': {  'year':'2',
             'week':'2:24',
             'topic':'Fear, Battling',
             'verse':'2Timothy+1:7' },
    '77': {  'year':'2',
             'week':'2:25',
             'topic':'Anxiety, Battling',
             'verse':'1Peter+5:6-8' },
    '78': {  'year':'2',
             'week':'2:26',
             'topic':'Suffering',
             'verse':'1Peter+5:9-11' },
    '79': {  'year':'2',
             'week':'2:27',
             'topic':'Security in God',
             'verse':'Proverbs+18:10' },
    '80': {  'year':'2',
             'week':'2:28',
             'topic':'Security in God',
             'verse':'Psalm+91:1-2' },
    '81': {  'year':'2',
             'week':'2:29',
             'topic':'Security in God',
             'verse':'Psalm+91:3-4' },
    '82': {  'year':'2',
             'week':'2:30',
             'topic':'Security in God',
             'verse':'Psalm+91:5-6' },
    '83': {  'year':'2',
             'week':'2:31',
             'topic':'Security in God',
             'verse':'Psalm+91:7-8' },
    '84': {  'year':'2',
             'week':'2:32',
             'topic':'Security in God',
             'verse':'Psalm+91:9-10' },
    '85': {  'year':'2',
             'week':'2:33',
             'topic':'Security in God',
             'verse':'Psalm+91:11-13' },
    '86': {  'year':'2',
             'week':'2:34',
             'topic':'Security in God',
             'verse':'Psalm+91:14-16' },
    '87': {  'year':'2',
             'week':'2:35',
             'topic':'Suffering',
             'verse':'1Peter+4:16' },
    '88': {  'year':'2',
             'week':'2:36',
             'topic':'Gospel',
             'verse':'John+3:16-17' },
    '89': {  'year':'2',
             'week':'2:37',
             'topic':'Salvation',
             'verse':'Acts+4:11-12' },
    '90': {  'year':'2',
             'week':'2:38',
             'topic':'Anger, Battling',
             'verse':'Proverbs+29:1,11' },
    '91': {  'year':'2',
             'week':'2:39',
             'topic':'Faithfulness (of God)',
             'verse':'Philippians+4:19' },
    '92': {  'year':'2',
             'week':'2:40',
             'topic':'Sin, Battling',
             'verse':'1Corinthians+10:13' },
    '93': {  'year':'2',
             'week':'2:41',
             'topic':'Work of Christ',
             'verse':'Isaiah+53:4-5' },
    '94': {  'year':'2',
             'week':'2:42',
             'topic':'Work of Christ',
             'verse':'Isaiah+53:6' },
    '95': {  'year':'2',
             'week':'2:43',
             'topic':'Gospel',
             'verse':'1Peter+2:24' },
    '96': {  'year':'2',
             'week':'2:44',
             'topic':'Suffering',
             'verse':'2Corinthians+4:17-18' },
    '97': {  'year':'2',
             'week':'2:45',
             'topic':'Life in Christ',
             'verse':'Galatians+2:20' },
    '98': {  'year':'2',
             'week':'2:46',
             'topic':'Gospel',
             'verse':'Romans+3:23-24' },
    '99': {  'year':'2',
             'week':'2:47',
             'topic':'Trusting God',
             'verse':'Hebrews+11:6' },
    '100': {  'year':'2',
              'week':'2:48',
              'topic':'Security in God',
              'verse':'Romans+14:7-9' },
    '101': {  'year':'2',
              'week':'2:49',
              'topic':'Salvation',
              'verse':'John+3:36' },
    '102': {  'year':'2',
              'week':'2:50',
              'topic':'Youth',
              'verse':'1Timothy+4:12' },
    '103': {  'year':'2',
              'week':'2:51',
              'topic':'Supremacy of Jesus',
              'verse':'1Corinthians+2:1-2' },
    '104': {  'year':'2',
              'week':'2:52',
              'topic':'Praise & Worship',
              'verse':'Revelation+5:12-13' },
    '105': {  'year':'3',
              'week':'3:01',
              'topic':'Fear, Battling',
              'verse':'Joshua+1:9' },
    '106': {  'year':'3',
              'week':'3:02',
              'topic':'Presence (of God)',
              'verse':'2Chronicles+16:9' },
    '107': {  'year':'3',
              'week':'3:03',
              'topic':'Supremacy of Jesus',
              'verse':'Philippians+3:7-8' },
    '108': {  'year':'3',
              'week':'3:04',
              'topic':'Salvation',
              'verse':'Philippians+3:9' },
    '109': {  'year':'3',
              'week':'3:05',
              'topic':'Suffering',
              'verse':'Philippians+3:10-11' },
    '110': {  'year':'3',
              'week':'3:06',
              'topic':'Salvation',
              'verse':'1Corinthians+1:18' },
    '111': {  'year':'3',
              'week':'3:07',
              'topic':'Trusting God',
              'verse':'Psalm+37:1-4' },
    '112': {  'year':'3',
              'week':'3:08',
              'topic':'Trusting God',
              'verse':'Psalm+37:5-8' },
    '113': {  'year':'3',
              'week':'3:09',
              'topic':'Guidance (of God)',
              'verse':'Psalm+37:23-24' },
    '114': {  'year':'3',
              'week':'3:10',
              'topic':'Endurance',
              'verse':'Hebrews+12:1' },
    '115': {  'year':'3',
              'week':'3:11',
              'topic':'Work of Christ',
              'verse':'Hebrews+12:2' },
    '116': {  'year':'3',
              'week':'3:12',
              'topic':'Praise & Worship',
              'verse':'Psalm+96:1-3' },
    '117': {  'year':'3',
              'week':'3:13',
              'topic':'Sovereignty of God',
              'verse':'Psalm+96:4-5' },
    '118': {  'year':'3',
              'week':'3:14',
              'topic':'Praise & Worship',
              'verse':'Psalm+96:6-8' },
    '119': {  'year':'3',
              'week':'3:15',
              'topic':'Praise & Worship',
              'verse':'Psalm+96:9-10' },
    '120': {  'year':'3',
              'week':'3:16',
              'topic':'Forgiveness',
              'verse':'Isaiah+43:25' },
    '121': {  'year':'3',
              'week':'3:17',
              'topic':'Life in Christ',
              'verse':'Romans+12:9-10' },
    '122': {  'year':'3',
              'week':'3:18',
              'topic':'Life in Christ',
              'verse':'Romans+12:11-13' },
    '123': {  'year':'3',
              'week':'3:19',
              'topic':'Life in Christ',
              'verse':'Romans+12:14-16' },
    '124': {  'year':'3',
              'week':'3:20',
              'topic':'Life in Christ',
              'verse':'Romans+12:17-19' },
    '125': {  'year':'3',
              'week':'3:21',
              'topic':'Life in Christ',
              'verse':'Romans+12:20-21' },
    '126': {  'year':'3',
              'week':'3:22',
              'topic':'Speech',
              'verse':'Proverbs+15:1' },
    '127': {  'year':'3',
              'week':'3:23',
              'topic':'Pride, Battling',
              'verse':'James+4:13-14' },
    '128': {  'year':'3',
              'week':'3:24',
              'topic':'Pride, Battling',
              'verse':'James+4:15-17' },
    '129': {  'year':'3',
              'week':'3:25',
              'topic':'Work of Christ',
              'verse':'Luke+19:10' },
    '130': {  'year':'3',
              'week':'3:26',
              'topic':'Word of the Lord',
              'verse':'Psalm+18:30-31' },
    '131': {  'year':'3',
              'week':'3:27',
              'topic':'Anxiety, Battling',
              'verse':'Philippians+4:6-7' },
    '132': {  'year':'3',
              'week':'3:28',
              'topic':'Sanctification',
              'verse':'Philippians+4:8' },
    '133': {  'year':'3',
              'week':'3:29',
              'topic':'Trusting God',
              'verse':'Psalm+42:11' },
    '134': {  'year':'3',
              'week':'3:30',
              'topic':'Faithfulness (of God)',
              'verse':'Isaiah+46:3-4' },
    '135': {  'year':'3',
              'week':'3:31',
              'topic':'Life in Christ',
              'verse':'Philippians+1:21' },
    '136': {  'year':'3',
              'week':'3:32',
              'topic':'Seeking God',
              'verse':'Jeremiah+29:11-14' },
    '137': {  'year':'3',
              'week':'3:33',
              'topic':'Contentment',
              'verse':'Proverbs+22:1' },
    '138': {  'year':'3',
              'week':'3:34',
              'topic':'Suffering',
              'verse':'Psalm+30:4-5' },
    '139': {  'year':'3',
              'week':'3:35',
              'topic':'Generosity',
              'verse':'Acts+20:35' },
    '140': {  'year':'3',
              'week':'3:36',
              'topic':'Sanctification',
              'verse':'Matthew+5:3-6' },
    '141': {  'year':'3',
              'week':'3:37',
              'topic':'Sanctification',
              'verse':'Matthew+5:7-10' },
    '142': {  'year':'3',
              'week':'3:38',
              'topic':'Suffering',
              'verse':'Matthew+5:11-12' },
    '143': {  'year':'3',
              'week':'3:39',
              'topic':'Sanctification',
              'verse':'1Corinthians+13:4-7' },
    '144': {  'year':'3',
              'week':'3:40',
              'topic':'Guidance (of God)',
              'verse':'Psalm+32:8-9' },
    '145': {  'year':'3',
              'week':'3:41',
              'topic':'Pride, Battling',
              'verse':'Proverbs+31:30' },
    '146': {  'year':'3',
              'week':'3:42',
              'topic':'Generosity',
              'verse':'Matthew+6:19-21' },
    '147': {  'year':'3',
              'week':'3:43',
              'topic':'Sanctification',
              'verse':'1Corinthians+10:31' },
    '148': {  'year':'3',
              'week':'3:44',
              'topic':'Work of Christ',
              'verse':'Romans+5:18-19' },
    '149': {  'year':'3',
              'week':'3:45',
              'topic':'Life in Christ',
              'verse':'John+5:39-40' },
    '150': {  'year':'3',
              'week':'3:46',
              'topic':'Life in Christ',
              'verse':'1Peter+2:9-11' },
    '151': {  'year':'3',
              'week':'3:47',
              'topic':'Word of the Lord',
              'verse':'Romans+10:17' },
    '152': {  'year':'3',
              'week':'3:48',
              'topic':'Humility of Christ',
              'verse':'Matthew+20:26-28' },
    '153': {  'year':'3',
              'week':'3:49',
              'topic':'Gospel',
              'verse':'2Corinthians+5:21' },
    '154': {  'year':'3',
              'week':'3:50',
              'topic':'Love (of God)',
              'verse':'1John+3:1-2' },
    '155': {  'year':'3',
              'week':'3:51',
              'topic':'Provision (of God)',
              'verse':'Ephesians+3:20-21' },
    '156': {  'year':'3',
              'week':'3:52',
              'topic':'Loving God',
              'verse':'Matthew+22:37-39' },
    '157': {  'year':'4',
              'week':'4:01',
              'topic':'Fear, Battling',
              'verse':'Isaiah+41:10' },
    '158': {  'year':'4',
              'week':'4:02',
              'topic':'Fear, Battling',
              'verse':'Isaiah+43:1-3' },
    '159': {  'year':'4',
              'week':'4:03',
              'topic':'Life in Christ',
              'verse':'John+14:6' },
    '160': {  'year':'4',
              'week':'4:04',
              'topic':'Life in Christ',
              'verse':'1Thessalonians+5:14-17' },
    '161': {  'year':'4',
              'week':'4:05',
              'topic':'Sanctification',
              'verse':'1Thessalonians+5:18-22' },
    '162': {  'year':'4',
              'week':'4:06',
              'topic':'Generosity',
              'verse':'Proverbs+3:9-10' },
    '163': {  'year':'4',
              'week':'4:07',
              'topic':'Discipline',
              'verse':'Proverbs+3:11-12' },
    '164': {  'year':'4',
              'week':'4:08',
              'topic':'Security in God',
              'verse':'John+10:27-30' },
    '165': {  'year':'4',
              'week':'4:09',
              'topic':'Obeying God',
              'verse':'Acts+5:29' },
    '166': {  'year':'4',
              'week':'4:10',
              'topic':'Praise & Worship',
              'verse':'Psalm+100:1-3' },
    '167': {  'year':'4',
              'week':'4:11',
              'topic':'Faithfulness (of God)',
              'verse':'Psalm+100:4-5' },
    '168': {  'year':'4',
              'week':'4:12',
              'topic':'Work of Christ',
              'verse':'Ephesians+2:1-3' },
    '169': {  'year':'4',
              'week':'4:13',
              'topic':'Work of Christ',
              'verse':'Ephesians+2:4-5' },
    '170': {  'year':'4',
              'week':'4:14',
              'topic':'Work of Christ',
              'verse':'Ephesians+2:6-7' },
    '171': {  'year':'4',
              'week':'4:15',
              'topic':'Salvation',
              'verse':'Ephesians+2:8-10' },
    '172': {  'year':'4',
              'week':'4:16',
              'topic':'Gospel',
              'verse':'Romans+5:8' },
    '173': {  'year':'4',
              'week':'4:17',
              'topic':'Salvation',
              'verse':'Romans+5:9-10' },
    '174': {  'year':'4',
              'week':'4:18',
              'topic':'Presence (of God)',
              'verse':'Psalm+139:1-3' },
    '175': {  'year':'4',
              'week':'4:19',
              'topic':'Sovereignty of God',
              'verse':'Psalm+139:4-5' },
    '176': {  'year':'4',
              'week':'4:20',
              'topic':'Presence (of God)',
              'verse':'Psalm+139:6-8' },
    '177': {  'year':'4',
              'week':'4:21',
              'topic':'Presence (of God)',
              'verse':'Psalm+139:9-10' },
    '178': {  'year':'4',
              'week':'4:22',
              'topic':'Presence (of God)',
              'verse':'Psalm+139:11-12' },
    '179': {  'year':'4',
              'week':'4:23',
              'topic':'Sovereignty of God',
              'verse':'Psalm+139:13-14' },
    '180': {  'year':'4',
              'week':'4:24',
              'topic':'Sovereignty of God',
              'verse':'Psalm+139:15-16' },
    '181': {  'year':'4',
              'week':'4:25',
              'topic':'Loving God',
              'verse':'Psalm+139:17-18' },
    '182': {  'year':'4',
              'week':'4:26',
              'topic':'Guidance (of God)',
              'verse':'Psalm+139:23-24' },
    '183': {  'year':'4',
              'week':'4:27',
              'topic':'Joy',
              'verse':'Proverbs+17:9,22' },
    '184': {  'year':'4',
              'week':'4:28',
              'topic':'Supremacy of Jesus',
              'verse':'Hebrews+1:1-2' },
    '185': {  'year':'4',
              'week':'4:29',
              'topic':'Supremacy of Jesus',
              'verse':'Hebrews+1:3-4' },
    '186': {  'year':'4',
              'week':'4:30',
              'topic':'Sovereignty of God',
              'verse':'Jeremiah+1:12' },
    '187': {  'year':'4',
              'week':'4:31',
              'topic':'Seeking God',
              'verse':'Psalm+9:9-10' },
    '188': {  'year':'4',
              'week':'4:32',
              'topic':'Goodness (of God)',
              'verse':'James+1:17' },
    '189': {  'year':'4',
              'week':'4:33',
              'topic':'Fear, Battling',
              'verse':'Psalm+27:1-3' },
    '190': {  'year':'4',
              'week':'4:34',
              'topic':'Seeking God',
              'verse':'Psalm+27:4-5' },
    '191': {  'year':'4',
              'week':'4:35',
              'topic':'Waiting on God',
              'verse':'Psalm+27:13-14' },
    '192': {  'year':'4',
              'week':'4:36',
              'topic':'Obeying God',
              'verse':'James+1:22-24' },
    '193': {  'year':'4',
              'week':'4:37',
              'topic':'Suffering',
              'verse':'Revelation+2:10' },
    '194': {  'year':'4',
              'week':'4:38',
              'topic':'Speech',
              'verse':'Proverbs+26:20' },
    '195': {  'year':'4',
              'week':'4:39',
              'topic':'Pride, Battling',
              'verse':'Jeremiah+9:23-24' },
    '196': {  'year':'4',
              'week':'4:40',
              'topic':'Gospel',
              'verse':'Romans+6:23' },
    '197': {  'year':'4',
              'week':'4:41',
              'topic':'Gospel',
              'verse':'1Corinthians+15:1-3' },
    '198': {  'year':'4',
              'week':'4:42',
              'topic':'Gospel',
              'verse':'1Peter+3:18' },
    '199': {  'year':'4',
              'week':'4:43',
              'topic':'Anxiety, Battling',
              'verse':'Psalm+55:22' },
    '200': {  'year':'4',
              'week':'4:44',
              'topic':'Sovereignty of God',
              'verse':'Psalm+127:1' },
    '201': {  'year':'4',
              'week':'4:45',
              'topic':'Obeying God',
              'verse':'James+4:7-8' },
    '202': {  'year':'4',
              'week':'4:46',
              'topic':'Word of the Lord',
              'verse':'Psalm+119:14-16' },
    '203': {  'year':'4',
              'week':'4:47',
              'topic':'Life in Christ',
              'verse':'John+15:7' },
    '204': {  'year':'4',
              'week':'4:48',
              'topic':'Trusting God',
              'verse':'Psalm+118:13-14' },
    '205': {  'year':'4',
              'week':'4:49',
              'topic':'Anger, Battling',
              'verse':'Proverbs+16:32' },
    '206': {  'year':'4',
              'week':'4:50',
              'topic':'Sin, Battling',
              'verse':'Hebrews+3:12-13' },
    '207': {  'year':'4',
              'week':'4:51',
              'topic':'Endurance',
              'verse':'1Corinthians+15:58' },
    '208': {  'year':'4',
              'week':'4:52',
              'topic':'Life in Christ',
              'verse':'John+11:25-26' },
    '209': {  'year':'5',
              'week':'5:01',
              'topic':'Sovereignty of God',
              'verse':'Daniel+2:20-21' },
    '210': {  'year':'5',
              'week':'5:02',
              'topic':'Work of Christ',
              'verse':'Matthew+9:13' },
    '211': {  'year':'5',
              'week':'5:03',
              'topic':'Security in God',
              'verse':'Psalm+121:1-2' },
    '212': {  'year':'5',
              'week':'5:04',
              'topic':'Security in God',
              'verse':'Psalm+121:3-4' },
    '213': {  'year':'5',
              'week':'5:05',
              'topic':'Security in God',
              'verse':'Psalm+121:5-6' },
    '214': {  'year':'5',
              'week':'5:06',
              'topic':'Security in God',
              'verse':'Psalm+121:7-8' },
    '215': {  'year':'5',
              'week':'5:07',
              'topic':'Sovereignty of God',
              'verse':'Romans+8:28' },
    '216': {  'year':'5',
              'week':'5:08',
              'topic':'Salvation',
              'verse':'Romans+8:29-30' },
    '217': {  'year':'5',
              'week':'5:09',
              'topic':'Anxiety, Battling',
              'verse':'Romans+8:31-32' },
    '218': {  'year':'5',
              'week':'5:10',
              'topic':'Security in God',
              'verse':'Romans+8:33-34' },
    '219': {  'year':'5',
              'week':'5:11',
              'topic':'Security in God',
              'verse':'Romans+8:35-37' },
    '220': {  'year':'5',
              'week':'5:12',
              'topic':'Security in God',
              'verse':'Romans+8:38-39' },
    '221': {  'year':'5',
              'week':'5:13',
              'topic':'Pride, Battling',
              'verse':'Galatians+6:14' },
    '222': {  'year':'5',
              'week':'5:14',
              'topic':'Sovereignty of God',
              'verse':'Numbers+23:19' },
    '223': {  'year':'5',
              'week':'5:15',
              'topic':'Gospel',
              'verse':'1Timothy+1:15' },
    '224': {  'year':'5',
              'week':'5:16',
              'topic':'Contentment',
              'verse':'Hebrews+13:5-6' },
    '225': {  'year':'5',
              'week':'5:17',
              'topic':'Love (of God)',
              'verse':'Lamentations+3:21-23' },
    '226': {  'year':'5',
              'week':'5:18',
              'topic':'Waiting on God',
              'verse':'Lamentations+3:24-26' },
    '227': {  'year':'5',
              'week':'5:19',
              'topic':'Love (of God)',
              'verse':'Lamentations+3:31-33' },
    '228': {  'year':'5',
              'week':'5:20',
              'topic':'Word of the Lord',
              'verse':'Colossians+3:16-17' },
    '229': {  'year':'5',
              'week':'5:21',
              'topic':'Trusting God',
              'verse':'Isaiah+26:3-4' },
    '230': {  'year':'5',
              'week':'5:22',
              'topic':'Word of the Lord',
              'verse':'Psalm+19:7-8' },
    '231': {  'year':'5',
              'week':'5:23',
              'topic':'Word of the Lord',
              'verse':'Psalm+19:9-11' },
    '232': {  'year':'5',
              'week':'5:24',
              'topic':'Life in Christ',
              'verse':'John+6:35' },
    '233': {  'year':'5',
              'week':'5:25',
              'topic':'Life in Christ',
              'verse':'Galatians+6:9-10' },
    '234': {  'year':'5',
              'week':'5:26',
              'topic':'Praise & Worship',
              'verse':'Psalm+34:1-3' },
    '235': {  'year':'5',
              'week':'5:27',
              'topic':'Seeking God',
              'verse':'Psalm+34:4-5' },
    '236': {  'year':'5',
              'week':'5:28',
              'topic':'Goodness (of God)',
              'verse':'Psalm+34:6-8' },
    '237': {  'year':'5',
              'week':'5:29',
              'topic':'Provision (of God)',
              'verse':'Psalm+34:9-11' },
    '238': {  'year':'5',
              'week':'5:30',
              'topic':'Speech',
              'verse':'Psalm+34:12-14' },
    '239': {  'year':'5',
              'week':'5:31',
              'topic':'Faithfulness (of God)',
              'verse':'Psalm+34:15-16' },
    '240': {  'year':'5',
              'week':'5:32',
              'topic':'Faithfulness (of God)',
              'verse':'Psalm+34:17-18' },
    '241': {  'year':'5',
              'week':'5:33',
              'topic':'Suffering',
              'verse':'Psalm+34:19-22' },
    '242': {  'year':'5',
              'week':'5:34',
              'topic':'Speech',
              'verse':'Colossians+4:6' },
    '243': {  'year':'5',
              'week':'5:35',
              'topic':'Word of the Lord',
              'verse':'John+8:31-32' },
    '244': {  'year':'5',
              'week':'5:36',
              'topic':'Life in Christ',
              'verse':'John+10:10' },
    '245': {  'year':'5',
              'week':'5:37',
              'topic':'Goodness (of God)',
              'verse':'Jeremiah+32:40' },
    '246': {  'year':'5',
              'week':'5:38',
              'topic':'Trusting God',
              'verse':'Psalm+73:25-26' },
    '247': {  'year':'5',
              'week':'5:39',
              'topic':'Sanctification',
              'verse':'Proverbs+4:23-24' },
    '248': {  'year':'5',
              'week':'5:40',
              'topic':'',
              'verse':'Proverbs+4:25-27' },
    '249': {  'year':'5',
              'week':'5:41',
              'topic':'Anger, Battling',
              'verse':'James+1:19-20' },
    '250': {  'year':'5',
              'week':'5:42',
              'topic':'Humility of Christ',
              'verse':'2Corinthians+8:9' },
    '251': {  'year':'5',
              'week':'5:43',
              'topic':'Sovereignty of God',
              'verse':'Psalm+77:13-14' },
    '252': {  'year':'5',
              'week':'5:44',
              'topic':'Fear, Battling',
              'verse':'Psalm+118:5-8' },
    '253': {  'year':'5',
              'week':'5:45',
              'topic':'Contentment',
              'verse':'1Timothy+6:6-7' },
    '254': {  'year':'5',
              'week':'5:46',
              'topic':'Salvation',
              'verse':'Psalm+79:9' },
    '255': {  'year':'5',
              'week':'5:47',
              'topic':'Goodness (of God)',
              'verse':'Psalm+84:10-12' },
    '256': {  'year':'5',
              'week':'5:48',
              'topic':'Anxiety, Battling',
              'verse':'1John+4:4' },
    '257': {  'year':'5',
              'week':'5:49',
              'topic':'Eternity',
              'verse':'1Corinthians+15:51-52 ' },
    '258': {  'year':'5',
              'week':'5:50',
              'topic':'Eternity',
              'verse':'Revelation+21:3' },
    '259': {  'year':'5',
              'week':'5:51',
              'topic':'Eternity',
              'verse':'Revelation+21:4' },
    '260': {  'year':'5',
              'week':'5:52',
              'topic':'Eternity',
              'verse':'Revelation+21:5-7' },
}
